services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - ${APP_PORT}:8080
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: Aomg15122001
      MYSQL_DATABASE: pe4log-dev
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
    driver: local
  db_data:
